let q = [
"“Difficulties in your life don’t come to destroy you, but to help you realize your hidden potential.” – Anonymous",
"Những biến cố trong đời xảy đến không phải để hạ gục bạn, chúng đến để giúp bạn nhận ra tiềm năng của mình. (Khuyết danh)",
"“If GOD brings you to it, He will bring you through it.” ― Anonymous",
"Nếu Thượng đế đã soi sáng cho bạn một đích đến, ngài sẽ cùng bạn vượt qua cả chặng đường. (Khuyết danh)    ",
"“Life is like riding a bicycle. To keep your balance, you must keep moving.” ― Albert Einstein",
"Sống trên đời giống như đang chạy một chiếc xe đạp vậy. Bạn muốn giữ thăng bằng thì buộc phải luôn tiến về phía trước. (Albert Einstein)",
"“God has a purpose for your pain, a reason for your struggle and a gift for your faithfulness. Don’t give up.” ― Anonymous",
"Thượng đế đã an bài tất cả, mọi nỗi đau đều có lý do, mọi khổ cực đều có nguyên nhân và lòng tin sẽ được bồi đáp với một món quà. Đừng bao giờ bỏ cuộc. (Khuyết danh)",
"“You only live once but you do it right ONCE IS ENOUGH.” ― Mae West",
"Ta chỉ sống duy nhất một lần; nhưng nếu sống đúng, chỉ một lần là đủ. (Mae West)",
"“Your life is your message to the world. Make sure it’s inspiring.” ― Anonymous",
"Cuộc đời bạn chính là thông điệp của bạn gửi đến thế giới này. Hãy truyền đi một thông điệp tích cực và đầy cảm hứng. (Khuyết danh)",
"“Rise up, start fresh, see the bright opportunity in each new day.” ― Anonymous",
"Khi một ngày mới sang trang, hãy ngẩng cao đầu, bắt đầu lại và mở mắt nhìn những cơ hội trước mắt mình. (Khuyết danh)",
"“Always end the day with a positive thought. No matter how hard things were, tomorrow’s a fresh opportunity to make it better.” ― Anonymous",
"Hãy đặt dấu chấm hết mỗi ngày bằng một suy nghĩ tích cực. Dù mọi việc có khó khăn thế nào, ngày mai luôn là một cơ hội mới để làm mọi thứ tốt hơn. (Khuyết danh)",
"“To be inspired is great, to inspire is incredible.” ― Anonymous",
"Được truyền cảm hứng là một điều tốt, và có thể truyền cảm hứng là một điều tuyệt vời. (Khuyết danh)",
"“Challenges are what make life interesting and overcoming them is what makes life meaningful.” ― Joshua J. Marine",
"Thử thách là thứ khiến cuộc sống này thú vị và vượt qua chúng là điều khiến cuộc sống này ý nghĩa. (Joshua J. Marine)",
"“You are not one type, nor belong to one category. You are a unique blend of personality needs. Live your needs for total fulfillment.” – Diana Detinger",
"Bạn không thuộc về bất kỳ một nhóm nào cả. Bạn là bản thể độc đáo duy nhất với những cá tính riêng. Vì vậy hãy sống thật với bản thân mình. (Diana Detinger)",
"“Life is without meaning. You bring meaning to it. The meaning of life is whatever you ascribe it to be. Being alive is the meaning.” – Joseph Campbell",
"Cuộc sống vốn không có nghĩa, ý nghĩa của cuộc sống nằm trong bạn đấy thôi. Cuộc sống này đều do một tay bạn vẽ nên. Và được sống là điều có nghĩa nhất. (Joseph Campbell)",
"“For the meaning of life differs from man to man, from day to day and from hour to hour. What matters, therefore, is not the meaning of life in general but rather the specific meaning of a person’s ","life at a given moment.” – Victor E. Frankl",
"Lý tưởng sống của mỗi người khác nhau, theo mỗi ngày sẽ khác đi, theo mỗi giờ sẽ thay đổi. Do đó lý tưởng sống thật ra không quan trọng, điều quan trọng là ý nghĩa của cuộc sống đối với mỗi người ","trong từng khoảng khắc của đời mình. (Victor E. Frankl)",
"“To believe in immortality is one thing, but it is first needful to believe in life.” – Robert Louis Stevenson",
"Trước khi vào sự bất tử, con người ta nên tin vào sự sống. (Robert Louis Stevenson)",
"“Just trust yourself, then you will know how to live.” – Johann Wolfgang von Goethe",
"Chỉ cần có lòng tin vào bản thân, bạn sẽ biết mình phải làm gì trong đời. (Johann Wolfgang von Goethe)",
"“Whatever we are, whatever we make of ourselves, is all we will ever have – and that, in its profound simplicity, is the meaning of life.” – Philip Appleman",
"Con người thật của ta, con người mà ta xây dựng nên và tất cả những gì ta có về cơ bản chính là ý nghĩa của cuộc sống này. (Philip Appleman)",
"“Love is our true destiny. We do not find the meaning of life by ourselves alone we find it with another.” – Thomas Merton",
"Tình yêu chính là lý tưởng thật sự của cuộc đời. Chúng ta chẳng thể nào tìm được ý nghĩa của cuộc sống này một mình mà không có một người tri kỷ. (Thomas Merton)",
"“Life is a fairy tale. Live it with wonder and amazement.” – Welwyn Wilton Katz",
"Cuộc sống này là một câu chuyện thần tiên nên hãy sống với ước mơ và những điều kỳ diệu. (Welwyn Wilton Katz)",
"“Do not fear failure but rather fear not trying.” – Roy T. Bennett",
"Thất bại không đáng sợ, bản thân không cố gắng mới đáng sợ. (Roy T. Bennett)",
"“Life takes on meaning when you become motivated, set goals and charge after them in an unstoppable manner.” – Les Brown",
"Cuộc sống này có nghĩ khi bạn có động lực, có mục tiêu và có quyết tâm theo đuổi chúng đến cùng. (Les Brown)",
"“We should give meaning to life, not wait for life gives us meaning.” – Stacy",
"Chúng nên nên cho cuộc đời này một ý nghĩa chứ đừng đợi cuộc đời này mang ý nghĩa gì đến cho mình. (Stacy)",
"“The first thing to do in life is to do with purpose what one purpose to do.” – Pablo Casals",
"Điều đầu tiên bạn cần làm trong đời mình là theo đuổi lý tưởng với lý tưởng của bản thân. (Pablo Casals)",
"“Everything in life is most fundamentally a gift. And you receive it best and you live it best by holding it with very open hands.” – Leo O’Donovan",
"Mọi việc trên đời vốn dĩ đều là một món quà. Nếu giang tay đón nhận, bạn sẽ nhận được món quà đẹp nhất. (Leo O’Donovan)",
"“The purpose of life is to discover your gift. The work of life is to develop it. The meaning of life is to give your gift away.” – David Viscott",
"Mục đích của cuộc sống này tìm ra món quà của bạn. Lý tưởng của cuộc sống này là làm món quà ấy tốt đẹp hơn. Ý nghĩa của cuộc sống này là trao lại món quà đó cho người khác. (David Viscott)",
"“To be what we are, and to become what we are capable of becoming, is the only end of life.” – Robert Louis Stevenson",
"Cái đích duy nhất trong đời này chính là sống thật và trở thành phiên bản tốt nhất của bản thân. (Robert Louis Stevenson)",
"“The meaning of life is not only to exist, to survive, but to move ahead, to go up, to achieve, to conquer.” – Arnold Schwarzenegger",
"Ta sống trên đời không phải chỉ để tồn tại mà là để vươn lên, để thành công và để chinh phục. (Arnold Schwarzenegger)",
"“Happiness is the meaning and the purpose of life, the whole aim and end of human existence.” – Aristotle",
"Hạnh phúc là ý nghĩa của cuộc sống này và cũng là đích đến cao cả nhất để con người tồn tại. (Aristotle)",
"“The true meaning of life is to plant trees, under whose shade you do not expect to sit.” – Nelson Henderson",
"Ý nghĩa thật sự của cuộc sống này là để trồng nên những tán cây mà không mong chờ mình được ngồi nghỉ mát dưới bóng của chúng. (Nelson Henderson)",
"“Doing what you love is the cornerstone of having abundance in your life.” – Wayne Dyer",
"Được làm điều mình thích là nền tảng để sống một cuộc đời ý nghĩa và han5hphuc1. (Wayne Dyer)",
"“If your dreams do not scare you, they are not big enough.” – Ellen Johnson Sirleaf",
"Một ước mơ không làm bạn chùn bước là một ước mơ chưa đủ lớn. (Ellen Johnson Sirleaf)",
"“If you don’t follow your heart, you might spend the rest of your life wishing you had.” – Brigitte Nicole",
"Nếu bây giờ không nghe theo con tim mình, bạn sẽ phải dành cả phần đời còn lại để ân hận về quyết định ngày hôm nay. (Brigitte Nicole)",
"“I just wish people would realize that anything is possible if you try. Dreams are made if people try.” – Terry Fox",
"Tôi chỉ mong mọi người nhận ra rằng chỉ cần có cố gắng, mọi thứ trên đời này đều có thể. Chỉ cần cố gắng, ước mơ sẽ thành hiện thực. (Terry Fox)",
"“A true test of character isn’t how you are on your best days but how you act on your worst days.” – Anonymous",
"Muốn biết tính cách thật của một người, đừng nhìn lúc anh ta huy hoàng nhất mà hãy nhìn cách anh ta hành xử vào lúc khốn cùng nhất. (Khuyết danh)",
"“Without hard work, nothing grows but weeds.” – Gordon B. Hinckley",
"Không có cố gắng thì chẳng có thứ gì phát sinh ngoài cỏ dại. (Gordon B. Hinckley)",
"“Your dream doesn’t have an expiration date. Take a deep breath and try again.” – Anonymous",
"Ước mơ đâu bao giờ hết hạn. Vì vậy hãy hít thở thật sâu và thử lại lần nữa nào. (Khuyết danh)",
"“You can never cross the ocean unless you have the courage to lose sight of the shore.” – Anonymous",
"Bạn sẽ không bao giờ vượt được đại dương nếu không có can đảm thôi không nhìn về phía đất liền. (Khuyết danh)",
"“Failure is not the opposite of success. It is a part of success.” – Anonymous",
"Thất bại không phải mặt trái của thành công. Thất bại là một phần đưa bạn đến thành công. (Khuyết danh)",
"“Let your faith be bigger than your fear.” – Anonymous",
"Hãy để lòng tin xóa mờ sự sợ hãi trong bạn. (Khuyết danh)",
"“Do not pray for an easy life, pray for the strength to endure a difficult one.” – Bruce Lee",
"Đừng mong có một cuộc sống dễ dàng, hãy cầu mình có sức mạnh để vượt qua khó khăn trong cuộc sống. (Bruce Lee)",
"“Challenges are what make life interesting and overcoming them is what makes life meaningful.” – Joshua J. Marine",
"Thử thách là thứ khiến cuộc sống này thú vị và vượt qua chúng là điều khiến cuộc sống này ý nghĩa. (Joshua J. Marine)",
"“Before defining what you want, know who you are.” – Diana Detinger",
"Trước khi xác định điều mình muốn, hãy xác định bạn là ai. (Diana Detinger)",
"“Keep your eyes in the stars and your feet on the ground.” – Theodore Roosevelt",
"Hãy hướng đôi mắt về phía những vì sao và đặt đôi chân thật vững trên mặt đất. (Theodore Roosevelt)",
"“Even if you’re on the right track, you’ll get run over if you just sit there.” – Will Rogers",
"Dù cho có đi đúng đường mà ngồi lỳ tại chỗ, bạn cũng sẽ bị dòng đời giẫm đạp mà thôi. (Will Rogers)",
"“You will never be happy if you continue to search for happiness consist of. You will never live if you are looking for the meaning of life.” – Albert Camus",
"Nếu cứ mãi đi thì ý nghĩa của hạnh phúc, bạn sẽ không bao giờ thấy hạnh phúc. Nếu cứ mãi đi tìm ý nghĩa của cuộc sống, bạn sẽ không bao giờ được sống thực sự. (Albert Camus)",
"“The best things in life make you sweaty.” – Edgar Allan Poe",
"Những thứ tốt đẹp nhất trên đời đều phải đánh đổi bằng mồ hôi và nước mắt. (Edgar Allan Poe)",
"“Life is problems. Loving is solving problems.” – Raymond E. Feist",
"Cuộc sống này là một chuỗi những câu đố. Và tình yêu chính là đáp án cho những câu đố ấy. (Raymond E. Feist)",
"“If there is meaning in life at all, then there must be meaning in suffering.” – Viktor E. Frankl",
"Nếu cuộc sống này thật sự có ý nghĩa thì phải chăng những đau khổ bạn gặp cũng đều có nguyên do. (Viktor E. Frankl)",
"“The secret to life is meaningless unless you discover it yourself.” – W. Somerset Maugham",
"Nếu không biết được bản thân mình là ai thì đi tìm ý nghĩa của cuộc sống chỉ là một việc vô nghĩa. (W. Somerset Maugham)",
"“Look at the stars. See their beauty. And in that beauty, see yourself.” – Draya Mooney",
"Hãy nhìn lên những vì sao để cảm nhận vẻ đẹp của chúng. Hãy nhìn vào tâm mình để để thấy vẻ đẹp của chính bạn. (Draya Mooney)",
"“Everyone now knows how to find the meaning of life within himself.’ – Kurt Vonnegut Jr.",
"Thật ra ai cũng biết cách tự tìm được ý nghĩa của cuộc sống trong chính bản thân mình. (Kurt Vonnegut Jr.)",
"“The greatest creation of power you have on earth, whether you are an angel, a spirit, a man or woman is to help others.” – Anne Rice",
"Quyền năng vĩ đại nhất trên đời này, bất kể bạn là thần tiên hay người phảm, chính là giúp đỡ người khác. (Anne Rice)",
"“The only purpose of our lives consists in waking each other up and being there for each other.” – Johanna Paungger",
"Ý nghĩa của cuộc đời này là mỗi ngày được gọi nhau dậy và ở cạnh bên nhau. (Johanna Paungger)",
"“Be a lover of the world, it is the only way to survive in it.” – Janosch",
"Hãy yêu lấy thế giới này vì đây là cách duy nhất để bạn tồn tại. (Janosch)",
"“Each man must look to himself to teach him the meaning of life. It is not something discovered: it is something molded.” – Antoine de Saint-Exupery",
"Mỗi người phải tự soi chiếu lại bản thân mình để tìm được ý nghĩa của cuộc sống. Vì ý nghĩa không phải thứ để bạn tìm kiếm mà là điều bạn đúc kết mà nên. (Antoine de Saint-Exupery)",
"“A life without cause is a life without effect.” – Barbarella",
"Sống không có lý tưởng thì chỉ sống vô nghĩa. (Barbarella)",
"“However vast the darkness, we must supply our own light.” – Stanley Kubrick",
"Dù bóng tối ngoài kia có rộng lớn thế nào, hãy luôn thắp lên ngọn đèn của chính mình. (Stanley Kubrick)",
"“The pure power of a life can manifest as beatitude, or as an unspeakable, sheer violence…” – Jane Bennett",
"Trong mắt mỗi người, cuộc sống này có thể là một phép lành nhưng cũng có thể là một chuỗi khổ đau không hồi kết… (Jane Bennett)",
"“You will have fewer regrets in life if you start focusing and taking responsibility for where you are and where you want to be.” – Deborah Day",
"Bạn sẽ không còn hối tiếc trong đời nếu tập trung và xác định được bạn đang ở đâu và muốn đi đâu trên đường đời này. (Deborah Day)",
"“Stop making excuses and start doing what makes you profoundly happy!” – Diana Dentinger",
"Hãy ngưng kiếm cớ và bắt đầu làm những việc khiến bạn thấy thật sự hạnh phúc nào! (Diana Dentinger)",
"“No one could teach you to be you… until now!” – Diana Dentinger",
"Không một ai có thể chỉ cho bạn cách sống thật với bản thân… ngoài chính bạn! (Diana Dentinger)",
"“Why settle for anything less than total life fulfillment. Start by filling yourself up with you.” – Diana Detinger",
"Tại sao bạn phải chấp nhận một cuộc sống tạm bợ trong khi bạn có thể bắt đầu sống hết sức mình ngay hôm nay. (Diana Detinger)",
"“Your life would never have a meaning if you don’t have a goal or purpose.”- Sunday Adelaja",
"Cuộc sống này sẽ không bao giờ có ý nghĩa trừ khi bạn tìm được lý tưởng sống của mình. (Sunday Adelaja)",
"“A life without concrete products is a meaningless one.” Sunday Adelaja",
"Sống mà không tạo ra được giá trị gì thì chỉ như sống một cuộc đời vô nghĩa. (Sunday Adelaja)",
"“Life is like a poetry, without meaning or purpose – it’s useless.” – Jawwad Zafar",
"Cuộc sống này giống như một bài thơ vậy. Thơ không ý thì chẳng thành thơ, sống không nghĩa thì chẳng phải sống. (Jawwad Zafar)",
"“Embrace your struggles. They are making you the person you were meant to be.” – Avijeet Das",
"Hãy trân trọng những vấp ngã trong đời vì chính chúng là thứ giúp tôi rèn nên con người mà bạn hằng tìm kiếm. (Avijeet Das)",
"“Life no longer felt meaningless. It felt stressful and terrifying, but it definitely didn’t feel meaningless.” – Donald Miller",
"Cuộc sống này chẳng còn vô nghĩa nữa. Đúng là nó đôi lúc khó khăn và đáng sợ nhưng cuộc sống này chưa bao giờ vô nghĩa.(Donald Miller)",
"“Do not fear the conflict, and do not flee from it; there is no struggle, there is no Virtue.” – Joyram",
"Đừng sợ hãi và bỏ chạy trước nghịch cảnh. Không có nghịch cảnh thì đức hạnh cũng sẽ không tồn tại trên đời. (Joyram)",
"“Sometimes the questions are complicated and the answers are simple.” – Dr. Seuss",
"Đôi lúc có những câu hỏi rất phức tạp nhưng câu trả lời lại rất đơn giản. (Dr. Seuss)",
"“It is better to be hated for what you are now than to be loved for you are not.” – Andre Gide",
"Thà bị ghét vì sống đúng với bản thân còn hơn phải giả tạo để nhận được lòng thương hại của kẻ khác.  (Andre Gide)",
"“Life isn’t about finding yourself. Life is about creating yourself.” – George Bernard Shaw",
"Bạn sống không phải để đi tìm bản thân mà là để tạo ra bản ngã của mình. (George Bernard Shaw)",
"“Things change. And friends leave. Life doesn’t stop for anybody.” – Stephen Chbosky",
"Mọi thứ rồi sẽ đổi thay. Có hợp rồi cũng sẽ tan. Cuộc sống sẽ không dừng lại vì ai cả. (Stephen Chbosky)",
"“Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness.” – Steve Maraboli",
"Hãy khóc, tha thứ, học hỏi và bước tiếp. Hãy để nước mắt hôm nay tưới cho những mầm cây hạnh phúc mai sau của bạn. (Steve Maraboli)",
"“It’s only after you’ve stepped outside your comfort zone that you begin to change, grow, and transform.” – Roy T. Bennett",
"Chỉ khi bước ra khỏi vùng an toàn của mình bạn mới có thể thay đổi, trưởng thành và hoàn thiện. (Roy T. Bennett)",
"“Do what is right, not what is easy nor what is popular.” – Roy. T. Bennett",
"Hãy làm điều đúng, đừng làm việc dễ hay việc mà người ngoài kia bảo bạn nên làm. (Roy. T. Bennett)",
"“At the end of the day, let there be no excuses, no explanation, no regrets.” – Steve Maraboli",
"Hãy sống để khi mỗi ngày kết thúc, bạn không có phải viện cớ, giải thích hoặc hối tiếc bất kỳ điều gì. (Steve Maraboli)",
"“Life can only be understood backward, but it must be lived forwards.” – Soren Kierkegaard",
"Bạn có thể ngồi suy ngẫm ngược về quá khứ để hiểu được cuộc đời này, nhưng để sống thì phải luôn nhìn về tương lai. (Soren Kierkegaard)",
"“Do not take life too seriously. You will never get out of it alive.” – Elbert Hubbard",
"Đừng sống quá nghiêm túc như thế vì vượt qua bể khổ là bạn cũng qua đời. (Elbert Hubbard)",
"“Stay focused, go after your dreams and keep moving toward your goals.” – LL Cool J",
"Hãy tập trung theo đuổi giấc mơ và luôn hướng về mục tiêu của mình. (LL Cool J)",
"“You are always a student, never a master. You have to keep moving forward.” – Conrad Hall",
"Con người ta vốn là một đứa học trò, không phải thầy dạy của cuộc sống này. Do đó để sống, bạn chỉ có thể học hỏi và tiến về phía trước. (Conrad Hall)",
"“Everything in life… has to have balance.” – Donna Karan",
"Mọi thứ trong đời này… đều cần có sự cân bằng. (Donna Karan)",
"“Life is not a problem to be solved, but a reality to be experienced.” – Soren Kierkegaard",
"Cuộc sống này không phải một câu hỏi để bạn đi tìm lời giải đáp, mà là một cơ hội để bạn trải nghiệm. (Soren Kierkegaard)",
"“Life is a journey that must be traveled no matter how bad the roads and accommodations.” – Oliver Goldsmith",
"Cuộc sống này là một hành trình bạn buộc phải đi dù đường có xấu hay điều kiện có vất vả đến thế nào. (Oliver Goldsmith)",
"“Work like you don’t need money. Love like you’ve never been hurt. Dance like nobody’s watching.” – Satchel Paige",
"Hãy làm việc như thế bạn không cần tiền. Hãy yêu như thể bạn chưa từng bị tổng thương. Hãy nhảy như thể không có ai đang nhìn bạn. (Satchel Paige)",
"“The best preparation for tomorrow is doing your best today.” – H. Jackson Brown, Jr.",
"Cố gắng hết sức mình trong hôm nay là sự chuẩn bị tốt nhất cho ngày mai. (H. Jackson Brown, Jr.)",
"“The secret of getting ahead is getting started.” – Mark Twain",
"Bí quyết để vươn lên là phải bắt đầu. (Mark Twain)",
"“Try not to become a man of success, but rather try to become a man of value.” – Albert Einstein",
"Đừng cố trở thành một người thành công, hãy cố gắng trở thành một người có giá trị. (Albert Einstein)",
"“Through hard work, perseverance and a faith in God you can live your dreams.” – Ben Carson",
"Hãy làm việc chăm chỉ, bền lòng phấn đấu và vững tin ở Chúa, bạn sẽ đạt được ước mơ của mình. (Ben Carson)",
"“Never give up. Today is hard, tomorrow will be worse, but the after tomorrow will be sunshine.” – Jack Ma",
"Đừng bao giờ bỏ cuộc. Hôm nay có thể khó khăn, ngày mai có thể tệ hơn, nhưng ngày tới nữa nhất định sẽ là một ngày tươi sáng. (Jack Ma)",
"“The good life is one inspired by love and guided by knowledge.” – Bertrand Russell",
"Một cuộc đời ý nghĩa được truyền cảm hứng bởi tình yêu và được dẫn dắt bới tri thức. (Bertrand Russell)",
"“Life is a progress, and not a station.” – Ralph Waldo Emerson",
"Cuộc sống là một chuyến đi, không phải một đích đến. (Ralph Waldo Emerson)",
"“Be not afraid of life. Believe that life is worth living for, and your belief will help create the fact.” – William James",
"Đừng sợ hãi cuộc sống này. Hãy tin rằng cuộc đời này thật đáng sống và chỉ cần có lòng tin, điều ấy sẽ thành sự thật. (William James)",
"“Nourish your nature. Be who you are meant to be.” – Diana Detinger",
"Hãy nuôi dưỡng con người thật của bạn và sống với chính bản thân mình. (Diana Detinger)",
"“Life is about making an impact, not making an income.” – Kevin Kruse",
"Ta sống trên đời để tạo ra ảnh hưởng, không phải để kiếm ra tiền. (Kevin Kruse)",
"“Too many of us are not living our dreams because we are living our fears.”  – Les Brown",
"Nhiều người không thể sống với giấc mơ của mình vì họ còn đang mải sống trong sự sợ hãi. (Les Brown)",
"“It’s not about how hard you can hit; it’s about how hard you can get hit and keep moving forward.” – Rocky Balboa",
"Việc bạn có đương đầu với khó khăn lớn đến đâu không quan trọng. Quan trọng là bạn có thể đương đầu với khó khăn và bước tiếp được trên đường đời này. (Rocky Balboa)",
"“Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.” – Roy T. Bennett",
"Đừng bao giờ để bị đánh bại bởi nỗi sợ, hãy để ước mơ trong tim dẫn lối cho bạn. (Roy T. Bennett)",
"“Do not wait to strike till the iron is hot, but make it hot by striking.” – William Butler Yeats",
"Đừng bao giờ đợi sắt nóng để có cơ hội rèn, hãy rèn để khiến thanh sắt kia phải tự nóng lên. (William Butler Yeats)",
"“Do not watch the clock. Do what it does. Keep going.” – Sam Levenson",
"Đừng bao giờ dõi mắt chờ đồng hồ. Hãy như nó, luôn chạy về phía trước. (Sam Levenson)",
"“Life must be lived and curiosity kept alive. One must never, for whatever reason, turn his back to life.” – Eleanor Roosevelt",
"Ta sinh ra là để sống và để tò mò học hỏi. Do đó đừng bao giờ vì bất kỳ lý do gì mà quay lưng lại với cuộc đời này. (Eleanor Roosevelt)",
"“Most important thing in life … is learning how to fall.” – Jeanette Walls",
"Bài học lớn nhất trong đời này… là học cách thất bại. (Jeanette Walls)"]
